# Generated by Django 5.0.6 on 2024-06-05 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=100)),
                ('description', models.TextField()),
                ('avg_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_pressure', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('belarus_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Valid format +375XXXXXXXXX', regex='^\\+375\\d{9}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('climate_autumn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autumn_country', to='agency.climate')),
                ('climate_spring', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spring_country', to='agency.climate')),
                ('climate_summer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summer_country', to='agency.climate')),
                ('climate_winter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winter_country', to='agency.climate')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('standard_room_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vip_room_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='agency.country')),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(choices=[(7, '1 week'), (14, '2 weeks'), (28, '4 weeks')])),
                ('departure_date', models.DateField()),
                ('promo_code_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_packages', to='agency.client')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.country')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.hotel')),
            ],
        ),
    ]
