# Generated by Django 5.0.6 on 2024-06-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelpackage',
            old_name='final_price',
            new_name='intermediate_price',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='client',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='promo_code_discount',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('departure_date', models.DateField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PR', 'In processing'), ('AC', 'Active'), ('IN', 'Inactive')], default='PR', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='agency.client')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.travelpackage')),
            ],
        ),
    ]
