# Generated by Django 5.0.6 on 2024-06-06 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_rename_final_price_travelpackage_intermediate_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='belarus_phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Valid format +375XXXXXXXXX', regex='^\\+375\\d{9}$')]),
        ),
    ]
