# Generated by Django 5.0.6 on 2024-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_client_belarus_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='name',
            field=models.CharField(default='Default Travel Package', max_length=50),
        ),
    ]
