# Generated by Django 5.0.6 on 2024-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_promocode_client_promo_codes_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
